# Generated by Django 3.2.12 on 2023-02-14 11:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_item'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Item',
        ),
    ]
